---

### Exercise 1:
Create a NumPy array of integers from 1 to 10.

```python
# Exercise 1
```

---

In [179]:
import numpy as np

In [180]:
a = np.arange(11)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### Exercise 2:
Create a 3x3 NumPy array filled with zeros.

```python
# Exercise 2
```

---

In [181]:
b = np.zeros((3,3))
b

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

### Exercise 3:
Create a NumPy array of 10 evenly spaced numbers between 0 and 5.

```python
# Exercise 3
```

---

In [182]:
c = np.linspace(0,5,10,endpoint=False)
c

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

### Exercise 4:
Create a 5x5 identity matrix using NumPy.

```python
# Exercise 4
```

---

In [183]:
d = np.eye(5)
d

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### Exercise 5:
Create a 4x4 matrix with random values between 0 and 1.

```python
# Exercise 5
```

---

In [184]:
import random
e = np.random.random((4,4))
e

array([[0.42053947, 0.55736879, 0.86055117, 0.72704426],
       [0.27032791, 0.1314828 , 0.05537432, 0.30159863],
       [0.26211815, 0.45614057, 0.68328134, 0.69562545],
       [0.28351885, 0.37992696, 0.18115096, 0.78854551]])

In [185]:
 np.random.seed(10)

In [186]:
f = np.random.rand(4,4)
f

array([[0.77132064, 0.02075195, 0.63364823, 0.74880388],
       [0.49850701, 0.22479665, 0.19806286, 0.76053071],
       [0.16911084, 0.08833981, 0.68535982, 0.95339335],
       [0.00394827, 0.51219226, 0.81262096, 0.61252607]])

In [187]:
 np.random.seed(0)

In [314]:
h = np.random.rand(4,4)
h

array([[0.82240674, 0.65342116, 0.72634246, 0.536923  ],
       [0.11047711, 0.40503561, 0.40537358, 0.32104299],
       [0.02995032, 0.73725424, 0.10978446, 0.60630813],
       [0.7032175 , 0.63478632, 0.95914225, 0.10329816]])

### Exercise 6:
Find the shape of a NumPy array.

```python
# Exercise 6
```

---

In [189]:
type(e)
e.shape
h.shape

(4, 4)

### Exercise 7:
Reshape a 1D NumPy array of 16 elements into a 4x4 matrix.

```python
# Exercise 7
```

---

In [190]:
i = np.arange(16)
i.reshape((4,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

### Exercise 8:
Find the data type of the elements in a NumPy array.

```python
# Exercise 8
```

---

In [191]:
i.dtype

dtype('int64')

### Exercise 9:
Create a NumPy array of integers from 1 to 100 and find all even numbers in the array.

```python
# Exercise 9
```

---

In [192]:
f = np.arange(1,100)
mask = f % 2 == 0
f[mask]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68,
       70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [193]:
A = [x for x in np.arange(1,101) if x%2==0]

### Exercise 10:
Generate a 6x6 matrix of random integers between 10 and 50.

```python
# Exercise 10
```

---

In [194]:
B = np.random.randint(10,50,(6,6))
B

array([[26, 15, 25, 10, 28, 45],
       [34, 39, 29, 29, 24, 49],
       [42, 11, 19, 42, 41, 20],
       [33, 45, 21, 38, 44, 10],
       [10, 46, 15, 48, 27, 25],
       [14, 41, 11, 11, 49, 45]])

### Exercise 11:
Slice a 2D NumPy array to extract a submatrix.

```python
# Exercise 11
```

---

In [195]:
C = np.arange(36).reshape((6,6))

In [196]:
C[:3,:]

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17]])

### Exercise 12:
Calculate the sum of all elements in a NumPy array.

```python
# Exercise 12
```

---

In [282]:
D = [x*2 for x in C]
D

[array([ 0,  2,  4,  6,  8, 10]),
 array([12, 14, 16, 18, 20, 22]),
 array([24, 26, 28, 30, 32, 34]),
 array([36, 38, 40, 42, 44, 46]),
 array([48, 50, 52, 54, 56, 58]),
 array([60, 62, 64, 66, 68, 70])]

### Exercise 13:
Calculate the mean, median, and standard deviation of a NumPy array.

```python
# Exercise 13
```

---

In [283]:
np.mean(C,axis=0)

array([15., 16., 17., 18., 19., 20.])

In [284]:
np.mean(C,axis=1)

array([ 2.5,  8.5, 14.5, 20.5, 26.5, 32.5])

In [285]:
np.median(C,axis=0)

array([15., 16., 17., 18., 19., 20.])

In [286]:
np.median(C,axis=1)

array([ 2.5,  8.5, 14.5, 20.5, 26.5, 32.5])

In [287]:
np.std(C,axis=0)

array([10.24695077, 10.24695077, 10.24695077, 10.24695077, 10.24695077,
       10.24695077])

In [288]:
np.std(C,axis=1)

array([1.70782513, 1.70782513, 1.70782513, 1.70782513, 1.70782513,
       1.70782513])

### Exercise 14:
Find the maximum and minimum values in a NumPy array.

```python
# Exercise 14
```

---

In [289]:
np.min(C)

0

In [290]:
np.max(D)

70

### Exercise 15:
Create a NumPy array of 20 random integers and find the index of the maximum value.

```python
# Exercise 15
```

---

In [291]:
e = np.random.random(20)
e

array([0.49777691, 0.58108193, 0.24155704, 0.16902541, 0.85958084,
       0.05853492, 0.4706209 , 0.115834  , 0.45705876, 0.97996233,
       0.42370635, 0.85712492, 0.11731556, 0.27125208, 0.40379274,
       0.39981214, 0.67138348, 0.34471813, 0.71376687, 0.6391869 ])

In [292]:
e.argmax()

9

### Exercise 16:
Create a NumPy array and reverse its elements.

```python
# Exercise 16
```

---

In [293]:
A = np.arange(25).reshape(5,5)
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [294]:
B = np.flip(A)
B

array([[24, 23, 22, 21, 20],
       [19, 18, 17, 16, 15],
       [14, 13, 12, 11, 10],
       [ 9,  8,  7,  6,  5],
       [ 4,  3,  2,  1,  0]])

### Exercise 17:
Create a 3x3 matrix and multiply it element-wise by another 3x3 matrix.

```python
# Exercise 17
```

---

In [295]:
F = np.dot(A,B)
F

array([[  90,   80,   70,   60,   50],
       [ 440,  405,  370,  335,  300],
       [ 790,  730,  670,  610,  550],
       [1140, 1055,  970,  885,  800],
       [1490, 1380, 1270, 1160, 1050]])

### Exercise 18:
Create a diagonal matrix from a given 1D array.

```python
# Exercise 18
```

---

In [296]:
A = np.diag(A)
A

array([ 0,  6, 12, 18, 24])

In [297]:
D = np.diag((2,5))
D

array([[2, 0],
       [0, 5]])

### Exercise 19:
Perform matrix multiplication on two 2D NumPy arrays.

```python
# Exercise 19
```

---

In [298]:
D

array([[2, 0],
       [0, 5]])

In [299]:
A

array([ 0,  6, 12, 18, 24])

In [300]:
F = F*F
F

array([[   8100,    6400,    4900,    3600,    2500],
       [ 193600,  164025,  136900,  112225,   90000],
       [ 624100,  532900,  448900,  372100,  302500],
       [1299600, 1113025,  940900,  783225,  640000],
       [2220100, 1904400, 1612900, 1345600, 1102500]])

### Exercise 20:
Flatten a 2D NumPy array into a 1D array.

```python
# Exercise 20
```

---

In [301]:
A = F.flatten()
A

array([   8100,    6400,    4900,    3600,    2500,  193600,  164025,
        136900,  112225,   90000,  624100,  532900,  448900,  372100,
        302500, 1299600, 1113025,  940900,  783225,  640000, 2220100,
       1904400, 1612900, 1345600, 1102500])

### Exercise 21:
Stack two NumPy arrays vertically.

```python
# Exercise 21
```

---

In [302]:
F = np.arange(9).reshape(3,3)
F

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [303]:
np.hstack(F)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [304]:
np.stack(F,axis=1)

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [305]:
np.vstack(F)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### Exercise 22:
Stack two NumPy arrays horizontally.

```python
# Exercise 22
```

---

In [306]:
np.hstack(F)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

### Exercise 23:
Split a NumPy array into multiple sub-arrays.

```python
# Exercise 23
```

---

In [307]:
np.array_split(F,3,axis=1)

[array([[0],
        [3],
        [6]]),
 array([[1],
        [4],
        [7]]),
 array([[2],
        [5],
        [8]])]

### Exercise 24:
Generate a random NumPy array and round each element to two decimal places.

```python
# Exercise 24
```

---

In [308]:
A = [np.random.rand(4) for x in np.arange(1)]
A

[array([0.39916115, 0.43176013, 0.6145277 , 0.07004219])]

### Exercise 25:
Find the unique elements of a NumPy array.

```python
# Exercise 25
```

---

In [309]:
np.unique(A)

array([0.07004219, 0.39916115, 0.43176013, 0.6145277 ])

### Exercise 26:
Replace all elements in a NumPy array that are less than a specific value with that value.

```python
# Exercise 26
```

---

In [310]:
for i in range(F.shape[0]):
    for j in range(F.shape[1]):
        if F[i][j] < 2:
            F[i][j] = 5

In [311]:
F

array([[5, 5, 2],
       [3, 4, 5],
       [6, 7, 8]])

### Exercise 27:
Find the cumulative sum of the elements in a NumPy array.

```python
# Exercise 27
```

---

In [312]:
np.cumsum(F)

array([ 5, 10, 12, 15, 19, 24, 30, 37, 45])

### Exercise 28:
Create a NumPy array and find the number of non-zero elements in it.

```python
# Exercise 28
```

---

In [313]:
np.nonzero(F)
F.

(array([0, 0, 0, 1, 1, 1, 2, 2, 2]), array([0, 1, 2, 0, 1, 2, 0, 1, 2]))

### Exercise 29:
Create a NumPy array of random integers and sort it in ascending order.

```python
# Exercise 29
```

---

In [317]:
A = np.random.randint(6,15,9)
A

array([ 9, 13,  7,  9, 13, 14, 14, 10, 11])

### Exercise 30:
Find the row-wise and column-wise sum of a 3x3 matrix.

```python
# Exercise 30
```

---

### Exercise 31:
Generate a 2D NumPy array with random values and normalize it (scale the values between 0 and 1).

```python
# Exercise 31
```

---

### Exercise 32:
Create two NumPy arrays and find the dot product.

```python
# Exercise 32
```

---

### Exercise 33:
Find the trace of a square NumPy matrix.

```python
# Exercise 33
```

---

### Exercise 34:
Create a 2D array and swap two rows.

```python
# Exercise 34
```

---

### Exercise 35:
Create a 1D NumPy array and convert it into a column vector.

```python
# Exercise 35
```

---

### Exercise 36:
Find the determinant of a 3x3 matrix.

```python
# Exercise 36
```

---

### Exercise 37:
Find the eigenvalues and eigenvectors of a 2x2 matrix.

```python
# Exercise 37
```

---

### Exercise 38:
Solve a system of linear equations using NumPy.

```python
# Exercise 38
```

---

### Exercise 39:
Add Gaussian noise to a NumPy array.

```python
# Exercise 39
```

---

### Exercise 40:
Create a 4x4 matrix and extract the diagonal elements.

```python
# Exercise 40
```

---

### Exercise 41:
Generate a NumPy array of 100 random values and clip the values to a range between 10 and 50.

```python
# Exercise 41
```

---

### Exercise 42:
Create a 2D NumPy array and replace all negative values with zero.

```python
# Exercise 42
```

---

### Exercise 43:
Find the inner and outer products of two NumPy arrays.

```python
# Exercise 43
```

---

### Exercise 44:25
Calculate the pairwise distances between points in a NumPy array.

```python
# Exercise 44
```

---

### Exercise 45:
Create a structured NumPy array with fields for `name`, `age`, and `height`.

```python
# Exercise 45
```

---

### Exercise 46:
Create a 5x5 matrix of random integers and count the occurrences of each unique value.

```python
# Exercise 46
```

---

### Exercise 47:
Generate a random 3x3 NumPy array and subtract the mean of each row from the corresponding row.

```python
# Exercise 47
```

---

### Exercise 48:
Create a NumPy array of random integers and check if any of the values are greater than 50.

```python
# Exercise 48
```

---

### Exercise 49:
Calculate the moving average of a 1D NumPy array.

```python
# Exercise 49
```

---

### Exercise 50:
Find the Pearson correlation coefficient between two NumPy arrays.

```python
# Exercise 50
```

---

### Exercise 51:
Convert a NumPy array of radians to degrees.

```python
# Exercise 51
```

---

### Exercise 52:
Create a random NumPy array and compute its variance and standard deviation.

```python
# Exercise 52
```

---

### Exercise 53:
Create a 2D NumPy array and find the indices of the maximum values along each axis.

```python
# Exercise 53
```

---

### Exercise 54:
Compute the inverse of a 2x2 NumPy matrix.

```python
# Exercise 54
```

---

### Exercise 55:
Create a NumPy array of 10 random values and standardize it (mean 0, variance 1).

```python
# Exercise 55
```

---

### Exercise 56:
Perform element-wise addition and subtraction on two NumPy arrays.

```python
# Exercise 56
```

---

### Exercise 57:
Create a NumPy array of random values and find the maximum element's index.

```python
# Exercise 57
```

---

### Exercise 58:
Create a 3x3 NumPy array and rotate it by 90 degrees.

```python
# Exercise 58
```

---

### Exercise 59:
Compute the Frobenius norm of a matrix.

```python
# Exercise 59
```

---

### Exercise 60:
Create a 3D NumPy array and slice out a subarray.

```python
# Exercise 60
```

---